up

diff --git a/scripts/flow b/scripts/flow
--- a/scripts/flow
+++ b/scripts/flow
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>
 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
@@ -18,6 +20,25 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-mkdocs>=0.17.1
-Pygments>=2.2
-pymdown-extensions>=3.4
+# Check if "yarn install" was executed
+if [[ ! -d "$(yarn bin)" ]]; then
+  echo "\"node_modules\" not found:"
+  echo "yarn install"
+  exit 1
+fi
+
+# Annotate source files
+"$(yarn bin)"/gulp assets:javascripts:annotate "$@"
+FLOW_JSDOC=$?
+
+# Run flow typecheck
+"$(yarn bin)"/flow check tmp --strip-root
+FLOW=$?
+
+# If one command failed, exit with error
+if [ $FLOW_JSDOC -gt 0 ] || [ $FLOW -gt 0 ]; then
+  exit 1
+fi;
+
+# Otherwise return with success
+exit 0
